### ISSUE TITLE
npm run start 出现错误

### ISSUE THREAD

**Issue by rookielzy** [hansneil/show_result#1]
您好，我的测试环境是Win 10 14393版本。
我先运行了 `npm run build`后
再运行 `npm run start` ， 本地服务器能够正常打开。

但是在选择了图片，Shooting Angle后，点击 Upload 后出现错误。

```test
> Server@0.0.0 start C:\Users\lzy\Desktop\Face_Detection_Demo-master\Face_Detection_Demo-master
> node ./bin/www

GET / 304 15.431 ms - -
GET /style.css 304 7.930 ms - -
GET /common.js 304 9.876 ms - -
GET /build.js 304 10.810 ms - -
C:\Users\lzy\Desktop\Face_Detection_Demo-master\Face_Detection_Demo-master\routes\upload.js:55
        var uploads = files.image;
                           ^

TypeError: Cannot read property 'image' of undefined
    at C:\Users\lzy\Desktop\Face_Detection_Demo-master\Face_Detection_Demo-master\routes\upload.js:55:28
    at C:\Users\lzy\Desktop\Face_Detection_Demo-master\Face_Detection_Demo-master\node_modules\multiparty\index.js:116:9
    at C:\Users\lzy\Desktop\Face_Detection_Demo-master\Face_Detection_Demo-master\node_modules\multiparty\index.js:108:9
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start"
npm ERR! node v7.7.2
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! Server@0.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Server@0.0.0 start script 'node ./bin/www'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the Server package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs Server
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls Server
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\lzy\Desktop\Face_Detection_Demo-master\Face_Detection_Demo-master\npm-debug.log
PS C:\Users\lzy\Desktop\Face_Detection_Demo-master\Face_Detection_Demo-master> npm run start
```

现在不知道如何解决了

**Comment by isMyShell** [comment]
怎么解决呢
